# Copyright (C) 2020-2022 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: '^easy_select2/static/easy_select2/vendor/'
      - id: trailing-whitespace

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        args: ['--show-source']
        exclude: '^(docs/source/|sampleproject/demoapp/migrations/)'

  - repo: https://github.com/pycqa/isort
    rev: 4.3.21
    hooks:
      - id: isort
