language: python
dist: trusty
group: stable
os: linux
python:
    - 2.7
    - 3.4
    - 3.5
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
install: pip install tox coveralls
script: tox
after_success:
    - coveralls
